Fix-up!

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -5,7 +5,7 @@
 # SPDX-License-Identifier: Apache-2.0
 #
 
-name: You have to cook it here.
+name: Bruh, stop toasting your PC, do buildbotting instead.
 on:
   workflow_dispatch:
     # Various inputs to simplify usage of workflow.
@@ -23,7 +23,7 @@ on:
       BUILD_DIFFERENT_ROM:
         description: "Command to initialize a different 'repo' project:"
         required: false
-        default: "echo 'Build Starting!'"
+        default: "path/to/idk"
       REMOVALS:
         description: "Folders to be removed before syncing:"
         required: false
@@ -34,7 +34,7 @@ on:
       LOCAL_MANIFEST_BRANCH:
         description: "Personal local manifest's branch:"
         required: false
-        default: 'codename'
+        default: 'branch'
       DEVICE_NAME:
         description: "Device's codename:"
         required: true
@@ -68,7 +68,10 @@ on:
 jobs:
   test:
     name: Build using foss.crave.io
+      # Change this to self-hosted after setting up devspace as github actions runner
     runs-on: ubuntu-latest
+    concurrency:
+      group: ${{ github.workflow }}-${{ github.ref }}
     steps:
       # Clean the workflow before initialization.
     - name: Cleanup
@@ -92,22 +95,53 @@ jobs:
         curl https://storage.googleapis.com/git-repo-downloads/repo >> "${HOME}/bin/repo"
         chmod a+x "${HOME}/bin/repo"
         sudo ln -sf "/home/${USER}/bin/repo" "/usr/bin/repo"
-
+      continue-on-error: true
+      
       # Generate 'git' credential in base of the workflow's author.
     - name: Set-up 'git' credential(s)
       run: |
         git config --global user.name "${{ github.actor }}"
         git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
 
+      # Test Your Personal 'Local Manifests' against The ROM
+    - name: Test Local Manifests
+      run: |
+             if [ "${{ github.event.inputs.BUILD_DIFFERENT_ROM }}" == "echo 'Build Starting!'" ]; then
+              case "${{ github.event.inputs.BASE_PROJECT }}" in
+                  "ArrowOS 13.1")
+                    repo init -u https://github.com/ArrowOS/android_manifest.git -b arrow-13.1 --depth=1
+                  ;;
+                  "DerpFest 13.0")
+                    repo init -u https://github.com/DerpFest-AOSP/manifest.git -b 13 --depth=1
+                  ;;
+                  "LineageOS 21.0")
+                    repo init -u https://github.com/LineageOS/android.git -b lineage-21.0 --git-lfs --depth=1
+                  ;;
+                  "LineageOS 20.0")
+                    repo init -u https://github.com/LineageOS/android.git -b lineage-20.0 --git-lfs --depth=1
+                  ;;
+              esac
+             else
+                      ${{ github.event.inputs.BUILD_DIFFERENT_ROM }}
+                      
+              fi
+              git clone ${{ github.event.inputs.LOCAL_MANIFEST }} --depth 1 -b ${{ github.event.inputs.LOCAL_MANIFEST_BRANCH }} .repo/local_manifests && \
+              timeout 1m repo sync --force-sync || { exit_code=$?; [ $exit_code -eq 124 ] || (echo "Error: Process failed with exit code $exit_code"; exit $exit_code); }
+              rm -rf .repo
+      timeout-minutes: 10  
+      
       # Download and configure 'crave'.
     - name: Configure the 'crave' environment
       run: |
-        curl -s https://raw.githubusercontent.com/accupara/crave/master/get_crave.sh | bash -s --
-        mv ${PWD}/crave ${HOME}/bin/
-        sudo ln -sf /home/${USER}/bin/crave /usr/bin/crave
-
-        envsubst < ${PWD}/crave.conf.sample >> ${PWD}/crave.conf
-        rm -rf ${PWD}/crave.conf.sample
+        if [ "${DCDEVSPACE}" == "1" ]; then
+        echo 'No need to set up crave, we are already running in devspace!'
+        else
+          curl -s https://raw.githubusercontent.com/accupara/crave/master/get_crave.sh | bash -s --
+          mv ${PWD}/crave ${HOME}/bin/
+          sudo ln -sf /home/${USER}/bin/crave /usr/bin/crave
+          envsubst < ${PWD}/crave.conf.sample >> ${PWD}/crave.conf
+          rm -rf ${PWD}/crave.conf.sample          
+        fi
       env:
         CRAVE_USERNAME: ${{  secrets.CRAVE_USERNAME  }}
         CRAVE_TOKEN: ${{  secrets.CRAVE_TOKEN  }}
@@ -125,11 +159,11 @@ jobs:
             crave set --projectID 64
           ;;
           "LineageOS 21.0")
-            repo init -u https://github.com/LineageOS/android.git -b lineage-21.0 --git-lfs --depth=1
+            repo init -u https://github.com/accupara/los21.git -b lineage-21.0 --git-lfs --depth=1
             crave set --projectID 72
           ;;
           "LineageOS 20.0")
-            repo init -u https://github.com/LineageOS/android.git -b lineage-20.0 --git-lfs --depth=1
+            repo init -u https://github.com/accupara/los20.git -b lineage-20.0 --git-lfs --depth=1
             crave set --projectID 36
           ;;
         esac
@@ -142,7 +176,7 @@ jobs:
            export CLEAN="clean"
         fi
 
-        crave run --no-patch --${CLEAN} "rm -rf ${PWD}/.repo/local_manifests/ ${{ github.event.inputs.REMOVALS }} && \
+        crave run --no-patch --${CLEAN} "rm -rf .repo/local_manifests/ ${{ github.event.inputs.REMOVALS }} && \
         # Clone local_manifests repository
         ${{ github.event.inputs.BUILD_DIFFERENT_ROM }} ; \
         git clone ${{ github.event.inputs.LOCAL_MANIFEST }} --depth 1 -b ${{ github.event.inputs.LOCAL_MANIFEST_BRANCH }} .repo/local_manifests && \
@@ -150,11 +184,10 @@ jobs:
         if [ ! $? == 0 ]; then \
           curl -o .repo/local_manifests ${{ github.event.inputs.LOCAL_MANIFEST }}; \
         fi \
-
+        
         # Sync the repositories
-        repo sync -c -j10 --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync  && \
-        rm -rf vendor/plros/prebuilt/apps/Cromite;
-        git clone https://gitlab.com/plros-lab/android_packages_apps_Cromite.git vendor/plros/prebuilt/apps/Cromite && \
+        repo sync -c -j\$(nproc --all) --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync  && \
+        
         # Set up build environment
         export BUILD_USERNAME=${{ github.actor }} ; \
         export BUILD_HOSTNAME=crave ; \
@@ -162,7 +195,7 @@ jobs:
 
         # Build the ROM
         lunch ${{ github.event.inputs.PRODUCT_NAME }}-${{ github.event.inputs.BUILD_TYPE }} && \
-        make clean && \
+        make installclean && \
         ${{ github.event.inputs.BUILD_COMMAND }}"
 
       # Only reach this wheter the user killed the workflow.
